#!/usr/bin/env python3
"""Generate manuscript figures from screening/prisma2020.json and master_counts.json (no hard-coded counts)."""
import json, pathlib
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import FancyBboxPatch

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE.parent / "manuscript" / "figures"
OUT.mkdir(parents=True, exist_ok=True)
P = json.loads((HERE.parent / "screening" / "prisma2020.json").read_text())
M = json.loads((HERE / "master_counts.json").read_text())

INK, INK2, MUTED, GRID, SURF = "#0b0b0b", "#52514e", "#8a8984", "#e4e3df", "#ffffff"
S1, S2, S3 = "#2a78d6", "#eb6834", "#1baf7a"  # validated categorical slots 1-3
plt.rcParams.update({"font.family": "DejaVu Sans", "font.size": 9, "text.color": INK, "axes.labelcolor": INK2,
                     "xtick.color": INK2, "ytick.color": INK2, "axes.edgecolor": MUTED})


def box(ax, x, y, w, h, text, fc="#f4f3f0", ec=MUTED, bold=False, fs=8.5):
    ax.add_patch(FancyBboxPatch((x, y), w, h, boxstyle="round,pad=0.02,rounding_size=0.02", fc=fc, ec=ec, lw=1))
    ax.text(x + w / 2, y + h / 2, text, ha="center", va="center", fontsize=fs,
            fontweight="bold" if bold else "normal", color=INK)


def arrow(ax, x1, y1, x2, y2):
    ax.annotate("", xy=(x2, y2), xytext=(x1, y1), arrowprops=dict(arrowstyle="-|>", color=INK2, lw=1))


def fig_flow():
    """PRISMA 2020 flow with a databases column and an other-methods column (counts from screening/prisma2020.json)."""
    fbox = lambda *a, **k: box(*a, **{"fs": 7.3, **k})
    d, o, t = P["databases"], P["other_methods"], M["by_type"]
    src = d["identified_by_source"]
    fig, ax = plt.subplots(figsize=(7.6, 7.4)); ax.set_xlim(0, 12); ax.set_ylim(0, 12); ax.axis("off")
    ax.text(1.8, 11.85, "Identification via databases", ha="center", fontsize=9, fontweight="bold", color=S1)
    ax.text(9.55, 11.85, "Identification via other methods", ha="center", fontsize=9, fontweight="bold", color=S2)
    fbox(ax, 0.1, 9.9, 3.4, 1.6, f"Records identified (9 Oct 2026)\nn = {d['identified_total']}\nScopus {src['Scopus']} | arXiv {src['arXiv']}\n"
        f"Semantic Scholar {src['SemanticScholar']}", fc="#e8f1fb", ec=S1)
    fbox(ax, 3.75, 9.9, 3.1, 1.6, f"Removed before screening\nduplicates (automatic):\n{d['duplicates_removed_automatic']}\n"
        f"version duplicates\n(manual): {d['version_duplicates_removed_manual']}", fc=SURF)
    fbox(ax, 7.2, 9.9, 4.7, 1.6, f"Records identified in 25 logged\nweb-search batches n = {o['identified_web_batches']}\n"
        f"duplicates within batches removed: {o['duplicates_within_web']}\nunique web records n = {o['web_records']}", fc="#fdeee7", ec=S2)
    fbox(ax, 0.1, 7.5, 3.4, 1.4, f"Records screened\n(title and abstract)\nn = {d['records_screened']}")
    fbox(ax, 3.75, 6.95, 3.1, 2.5, f"Records excluded n = {d['final_excluded']}\nstage 1 rule-based: {d['excluded_stage1_rule']}\n"
        f"(audited sample, then\nrescue screen: {d['excluded_rescue_screen']})\nstage 2 title/abstract: {d['excluded_stage2_title_abstract']}\n"
        f"reinstated at\nreconciliation: {d['excluded_stage1_rule'] + d['excluded_rescue_screen'] + d['excluded_stage2_title_abstract'] - d['final_excluded']}", fc=SURF, fs=7.0)
    fbox(ax, 7.2, 7.5, 4.7, 1.4, f"Already retrieved by the database\nsearch (counted there) n = {o['already_retrieved_by_databases']}\n"
        f"Records assessed n = {o['records_assessed']}")
    ex = o["excluded_by_code"]
    fbox(ax, 7.2, 5.1, 4.7, 1.6, f"Records excluded n = {sum(ex.values())}\nE6 unverifiable metadata: {ex['E6']}\n"
        f"E1 out of scope: {ex['E1']}\nE3 non-archival post: {ex['E3']}", fc=SURF)
    fbox(ax, 0.1, 4.2, 3.4, 1.5, f"Eligible records\nn = {d['final_included'] + d['final_context']}")
    fbox(ax, 3.75, 4.2, 3.1, 1.5, f"Contextual or\nmethodological references\n(not charted) n = {d['final_context']}", fc=SURF)
    fbox(ax, 7.2, 3.0, 4.7, 1.5, f"Eligible records n = {o['final_included'] + o['final_context']}\n"
        f"contextual references\n(not charted): {o['final_context']}")
    fbox(ax, 1.6, 0.35, 8.8, 1.8, f"Studies included in the evidence map  n = {P['total_included']}\n"
        f"via databases {d['final_included']} | via other methods only {o['final_included']}\n"
        f"preprints {t['Preprint']} | peer-reviewed {t['Peer-reviewed']} | grey literature {t['Grey literature']}",
        fc="#e8f1fb", ec=S1, bold=True, fs=8)
    for x in (1.8,):
        arrow(ax, x, 9.9, x, 8.9); arrow(ax, x, 7.5, x, 5.7); arrow(ax, x, 4.2, x, 2.15)
    arrow(ax, 9.55, 9.9, 9.55, 8.9); arrow(ax, 9.55, 7.5, 9.55, 6.7); arrow(ax, 9.55, 5.1, 9.55, 4.5); arrow(ax, 9.55, 3.0, 9.55, 2.15)
    arrow(ax, 3.5, 10.7, 3.75, 10.7); arrow(ax, 3.5, 8.2, 3.75, 8.2); arrow(ax, 3.5, 4.95, 3.75, 4.95)
    ax.text(0.1, -0.15, "Records found by both routes are counted once, in the databases column. All counts are generated by "
            "search/dedup.py and screening/merge.py.", fontsize=6.5, color=INK2)
    fig.savefig(OUT / "fig1_selection_flow.png", dpi=300, bbox_inches="tight", facecolor=SURF); plt.close(fig)


def fig_framework():
    fig, ax = plt.subplots(figsize=(7.2, 3.8)); ax.set_xlim(0, 12); ax.set_ylim(0, 6.3); ax.axis("off")
    layers = [("L1  CONTEXT\nSIGNAL", "Evaluation properties\nmaking it\nrecognisable: format,\nrealism, synthetic\nprompts, honeypot cues"),
              ("L2  AWARENESS", "Model recognition:\nrepresented (probes),\nverbalised (CoT),\nelicited\n(classification)"),
              ("L3  BEHAVIOURAL\nDIVERGENCE", "Evaluation-conditioned\nbehaviour: sandbagging,\nalignment/eval faking,\nstrategic dishonesty,\ntest/grader gaming"),
              ("L4  VALIDITY\nCONSEQUENCE", "Score-to-deployment\ngap and responses:\ndetection, elicitation,\nsuppression, redesign,\nreporting")]
    x = 0.2
    for i, (h, b) in enumerate(layers):
        box(ax, x, 3.3, 2.7, 1.3, h, fc="#e8f1fb" if i < 3 else "#fdeee7", ec=S1 if i < 3 else S2, bold=True, fs=8)
        box(ax, x, 0.5, 2.7, 2.5, b, fc=SURF, fs=7)
        if i < 3:
            arrow(ax, x + 2.7, 3.95, x + 3.0, 3.95)
        x += 3.0
    ax.annotate("", xy=(1.55, 4.75), xytext=(10.55, 4.75),
                arrowprops=dict(arrowstyle="-|>", color=S2, lw=1, connectionstyle="arc3,rad=0.12", linestyle="--"))
    ax.text(6.0, 5.95, "Countermeasures act back on L1-L3 (realism engineering, steering, elicitation, training)",
            ha="center", fontsize=8, color=INK2)
    fig.savefig(OUT / "fig4_framework.png", dpi=300, bbox_inches="tight", facecolor=SURF); plt.close(fig)


def fig_years():
    yt = M["by_year_type"]; years = sorted(yt)
    types = [("Peer-reviewed", S1), ("Preprint", S2), ("Grey literature", S3)]
    fig, ax = plt.subplots(figsize=(6.0, 3.2))
    bottom = [0] * len(years)
    for name, c in types:
        vals = [yt[y].get(name, 0) for y in years]
        ax.bar(years, vals, bottom=bottom, color=c, width=0.6, label=name, edgecolor=SURF, linewidth=2)
        bottom = [b + v for b, v in zip(bottom, vals)]
    for x, b in zip(years, bottom):
        ax.text(x, b + 2, str(b), ha="center", fontsize=8, color=INK)
    ax.set_ylabel("Included studies (n)"); ax.spines[["top", "right"]].set_visible(False)
    ax.yaxis.grid(True, color=GRID, lw=0.6); ax.set_axisbelow(True)
    ax.legend(frameon=False, fontsize=8, loc="upper left")
    ax.text(1.0, -0.22, "2026 covers January to early October only.", transform=ax.transAxes, ha="right", fontsize=7, color=INK2)
    fig.savefig(OUT / "fig2_sources_by_year.png", dpi=300, bbox_inches="tight", facecolor=SURF); plt.close(fig)


def fig_map():
    lm = M["layer_x_method"]
    layers = ["L1 Context signal", "L2 Awareness", "L3 Behavioural divergence", "L4 Validity consequence and response"]
    methods = ["Behavioural contrast (black-box)", "Benchmark / environment construction", "Reasoning-trace / transcript monitoring",
               "White-box (probes, steering, features)", "Training- or weight-based (elicitation, organisms)", "Developer or third-party audit"]
    data = [[lm.get(l, {}).get(m, 0) for m in methods] for l in layers]
    ramp = matplotlib.colors.LinearSegmentedColormap.from_list("blue", ["#f3f7fd", "#9cc3ef", "#2a78d6", "#123f78"])
    fig, ax = plt.subplots(figsize=(7.2, 3.4))
    im = ax.imshow(data, cmap=ramp, aspect="auto")
    vmax = max(max(r) for r in data)
    for i, r in enumerate(data):
        for j, v in enumerate(r):
            ax.text(j, i, v, ha="center", va="center", fontsize=9, color="#ffffff" if v > vmax * 0.55 else INK)
    short = ["Behavioural\ncontrast", "Benchmark /\nenvironment", "Reasoning-trace\nmonitoring", "White-box\n(probes, steering)", "Training- /\nweight-based", "Developer /\nthird-party audit"]
    ax.set_xticks(range(len(methods)), short, fontsize=7)
    ax.set_yticks(range(len(layers)), [l.replace(" and ", "\nand ") for l in layers], fontsize=8)
    ax.set_xticks([x - 0.5 for x in range(1, len(methods))], minor=True); ax.set_yticks([y - 0.5 for y in range(1, len(layers))], minor=True)
    ax.grid(which="minor", color=SURF, lw=2); ax.tick_params(which="both", length=0)
    for s in ax.spines.values(): s.set_visible(False)
    cb = fig.colorbar(im, ax=ax, fraction=0.03, pad=0.02); cb.outline.set_visible(False); cb.set_label("Included studies (n)", fontsize=8)
    fig.savefig(OUT / "fig3_evidence_map.png", dpi=300, bbox_inches="tight", facecolor=SURF); plt.close(fig)


if __name__ == "__main__":
    fig_flow(); fig_framework(); fig_years(); fig_map()
    print(sorted(p.name for p in OUT.iterdir()))
